project:
  awsSetup:
    bucket: projects.irll
    cpu: 2
    memory: 10
    region: ca-central-1
    rootDomain: irll.net
  events:
    startServerStep: 1
    stopServerStep: 3
  id: fingerprint-demo
  live: true
  maxRuntime: 30
  name: fingerprint-demo
  researcher: Nadeen
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: exampleConsent.html
    2: game
    3: exampleThank.html
    finalStep: exampleThank.html
  teamMembers: null
  useAWS: false
trial:
  actionBufferLifespan: 1
  actionSpace: null
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  fingerprint: true
  frameRateStepSize: 5
  game: fingerprint
  instructions:
  - Scroll (mouse), pinch (touchpad/mousepad), double-click or use control keys to
    zoom
  - Click and drag the canvas to pan around the canvas
  - Click and drag a marker to move it
  - Use sliders to adjust image appearance
  - Click on "Add Marker" and select target location on image to add a marker, or
    right-click on the image
  - Click on "Get Feedback" to get feedback on your image. Green means that removing
    it will decrease your score, and red means that removing it will increase your
    score.
  maxEpisodes: 20
  maxFrameRate: 60
  maxScore: 2242
  minFrameRate: 1
  minMinutiae: 1
  projectId: fingerprint-demo
  s3upload: false
  startingFrameRate: 30
  ui:
  - stop
  - brightness
  - contrast
  - saturation
  - hue
  - undo
  - redo
  - addMinutia
  - resetImage
  - submitImage
  - getFeedback
