project:
  awsSetup:
    bucket: projects.irll
    containerName: new-cognitive-tutor
    cpu: 2
    memory: 10
    region: ca-central-1
    repository: new-cognitive-tutor
    repositoryUri: 237796709103.dkr.ecr.ca-central-1.amazonaws.com/new-cognitive-tutor
    rootDomain: irll.net
  bucket: projects.irll
  ecsTask: new-cognitive-tutor
  events:
    startServerStep: 1
    stopServerStep: 17
  id: new-cognitive-tutor
  live: true
  maxRuntime: 30
  name: new-cognitive-tutor-pilot
  researcher: Nadeen
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: 1_consentForm.html
    2: 2_intro_instructions.html
    3: 3_flight_planning_intro.html
    4: 4_flight_planning_intro2.html
    5: 5_node_inspector.html
    6: 6_rewards_costs.html
    7: 7_graph_structure_info.html
    8: 8_train_test_instruction.html
    9: 9_cognitive_tutor_instructions.html
    10: 10_quiz_instructions.html
    11: game
    finalStep: exampleThank.html
  teamMembers: null
  useAWS: true
trial:
  actionBufferLifespan: 1
  actionSpace: null
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  fingerprint: true
  frameRateStepSize: 5
  game: fingerprint
  instructions:
  - Scroll (mouse), pinch (touchpad/mousepad), double-click or use control keys to
    zoom
  - Click and drag the canvas to pan around the canvas
  - Click and drag a marker to move it
  - Use sliders to adjust image appearance
  - Click on "Add Marker" and select target location on image to add a marker, or
    right-click on the image
  - Click on "Get Feedback" to get feedback on your image. Green means that removing
    it will decrease your score, and red means that removing it will increase your
    score.
  maxEpisodes: 42
  maxFrameRate: 60
  maxScore: 2242
  minFrameRate: 1
  minMinutiae: 1
  projectId: new-cognitive-tutor
  s3upload: true
  startingFrameRate: 30
  ui:
  - stop
  - brightness
  - contrast
  - saturation
  - hue
  - undo
  - redo
  - addMinutia
  - resetImage
  - submitImage
  - getFeedback
